- hosts: localhost
  become: true
  tasks:
    - name: Install kubectl (if missing)
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl

    - name: Apply Kubernetes manifests
      shell: kubectl apply -f ~/portfolio/k8s-manifests/
