---
- name: Install k3s on Amazon Linux 2
  hosts: localhost
  become: yes
  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install dependencies
      yum:
        name:
          - curl
          - git
          - python3-pip
        state: present

    - name: Install Ansible
      pip:
        name: ansible
        state: present

    - name: Install k3s without SELinux
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable-agent" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Symlink kubectl to k3s
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link
        force: yes

    - name: Ensure k3s service is running
      systemd:
        name: k3s
        state: started
        enabled: yes
